import { describe, expect, it } from "vitest";

import fixture from "../fixtures/balance.json";
import definitions from "../src/data/definitions.json";
import scenarios from "../src/data/scenarios.json";
import type { Definitions, Ingredient } from "../src/core/types";

/**
 * The cross-language half of the balance gate.
 *
 * `fixtures/balance.json` is generated by Rust from the shipped catalogues, and the Rust suite
 * asserts it computes exactly those numbers. This side recomputes the parts that are pure
 * arithmetic over `definitions.json` — the recipe-tree expansion, the fuel round trip, the machine
 * rates — from scratch, and asserts it lands on the same figures. Two independent expansions
 * agreeing is what makes the fixture evidence; one implementation agreeing with its own output
 * would only say the file was written.
 *
 * The parts that are not pure arithmetic over the catalogue — what a world preset actually
 * generates, what an extraction site is worth — stay Rust's, because they are the generator's
 * answers and re-deriving those here would be a second world generator.
 *
 * If this fails after a deliberate tuning pass, regenerate with
 * `UPDATE_BALANCE_FIXTURE=1 cargo test balance_fixture` and read the diff.
 */

const catalogue = definitions as Definitions;

function openingWork(
  ingredients: Ingredient[],
  machines: string[],
): [number, number] {
  const total: [number, number] = [0, 0];
  const walk = (itemId: number, quantity: number): void => {
    const recipe = catalogue.recipes.find(
      (recipe) => recipe.output.item_id === itemId,
    );
    if (!recipe) return;
    const crafts = Math.ceil(quantity / recipe.output.quantity);
    const machine = catalogue.buildings
      .filter(
        (building) =>
          machines.includes(building.key) &&
          (building.recipe_ids
            ? building.recipe_ids.includes(recipe.id)
            : building.recipe_category === recipe.category),
      )
      .sort(
        (a, b) =>
          (a.duration_multiplier ?? 1) - (b.duration_multiplier ?? 1) ||
          a.id - b.id,
      )[0];
    if (!machine) throw new Error(`No machine for ${recipe.key}`);
    total[machine.manual_work ? 1 : 0] +=
      crafts * recipe.duration * (machine.duration_multiplier ?? 1);
    recipe.inputs.forEach((input) =>
      walk(input.item_id, crafts * input.quantity),
    );
  };
  ingredients.forEach((input) => walk(input.item_id, input.quantity));
  return total;
}

/**
 * The bills of the contract stages an opening has to deliver before it can start.
 *
 * Four technologies are granted by finishing a stage and cannot be bought at any price, so an
 * opening that needs one owes the hub that stage's delivery on top of its own. A sentinel bill is
 * skipped for the same reason Rust skips it: it exists to never be met.
 */
function commissionedRequirements(stages: string[]): Ingredient[] {
  return stages.flatMap((key) => {
    const stage = (
      scenarios as unknown as {
        scenarios: {
          contract: { stages: { key: string; requirements: Ingredient[] }[] };
        }[];
      }
    ).scenarios
      .flatMap((scenario) => scenario.contract.stages)
      .find((stage) => stage.key === key);
    expect(stage, `${key} is a shipped contract stage`).toBeDefined();
    const requirements = stage!.requirements;
    return requirements.some((need) => need.quantity > 10_000)
      ? []
      : requirements;
  });
}

/** Recompute construction work with only the suppliers that already exist at each step. */
function stagedOpeningWork(
  order: string[],
  wanted: Ingredient[],
): [number, number] {
  const built: string[] = [];
  const total: [number, number] = [0, 0];
  for (const key of order) {
    const station = catalogue.buildings.find(
      (building) => building.key === key,
    )!;
    expect(built).not.toContain(key);
    const work = openingWork(station.construction_cost, built);
    total[0] += work[0];
    total[1] += work[1];
    if ((station.power_draw ?? 0) > 0) {
      expect(
        catalogue.buildings.some(
          (building) =>
            built.includes(building.key) && (building.power_output ?? 0) > 0,
        ),
      ).toBe(true);
    }
    built.push(key);
  }
  const work = openingWork(wanted, built);
  return [total[0] + work[0], total[1] + work[1]];
}

// Exact rationals, for the same reason Rust uses them: a kiln fires three bricks at once, so a
// pump that wants four of them costs four thirds of a batch, and rounding that at every step of a
// tree and then comparing two buildings compares rounding errors.
interface Ratio {
  num: number;
  den: number;
}

function gcd(a: number, b: number): number {
  return b === 0 ? Math.max(a, 1) : gcd(b, a % b);
}

function ratio(num: number, den = 1): Ratio {
  const divisor = gcd(Math.abs(num), Math.abs(den));
  return { num: num / divisor, den: den / divisor };
}

function add(left: Ratio, right: Ratio): Ratio {
  return ratio(
    left.num * right.den + right.num * left.den,
    left.den * right.den,
  );
}

function times(value: Ratio, factor: number): Ratio {
  return ratio(value.num * factor, value.den);
}

function over(value: Ratio, divisor: number): Ratio {
  return ratio(value.num, value.den * divisor);
}

/** Thousandths, rounded half up — the same one rounding, at the same edge, Rust applies. */
function milli(value: Ratio): number {
  return Math.floor((value.num * 1000 + Math.floor(value.den / 2)) / value.den);
}

const itemById = new Map(catalogue.items.map((item) => [item.id, item]));
const recipeFor = new Map(
  catalogue.recipes.map((recipe) => [recipe.output.item_id, recipe]),
);
const keyOf = (id: number) => itemById.get(id)?.key ?? `item-${id}`;

const bestFuel = catalogue.items
  .filter((item) => item.fuel_value)
  .reduce((best, item) =>
    (item.fuel_value ?? 0) > (best.fuel_value ?? 0) ? item : best,
  );

interface Expansion {
  raw: Map<number, Ratio>;
  energy: Ratio;
  ticks: Ratio;
  batch: Map<number, number>;
  batchEnergy: number;
  batchTicks: number;
  depth: number;
}

function depthOf(itemId: number): number {
  const recipe = recipeFor.get(itemId);
  if (!recipe) return 0;
  return 1 + Math.max(...recipe.inputs.map((input) => depthOf(input.item_id)));
}

function expand(ingredients: Ingredient[]): Expansion {
  const result: Expansion = {
    raw: new Map(),
    energy: ratio(0),
    ticks: ratio(0),
    batch: new Map(),
    batchEnergy: 0,
    batchTicks: 0,
    depth: 0,
  };

  const exact = (itemId: number, quantity: Ratio) => {
    const recipe = recipeFor.get(itemId);
    if (!recipe) {
      result.raw.set(itemId, add(result.raw.get(itemId) ?? ratio(0), quantity));
      return;
    }
    const crafts = over(quantity, Math.max(recipe.output.quantity, 1));
    result.energy = add(result.energy, times(crafts, recipe.fuel ?? 0));
    result.ticks = add(result.ticks, times(crafts, recipe.duration));
    for (const input of recipe.inputs)
      exact(input.item_id, times(crafts, input.quantity));
  };

  const whole = (itemId: number, quantity: number) => {
    const recipe = recipeFor.get(itemId);
    if (!recipe) {
      result.batch.set(itemId, (result.batch.get(itemId) ?? 0) + quantity);
      return;
    }
    const crafts = Math.ceil(quantity / Math.max(recipe.output.quantity, 1));
    result.batchEnergy += crafts * (recipe.fuel ?? 0);
    result.batchTicks += crafts * recipe.duration;
    for (const input of recipe.inputs)
      whole(input.item_id, crafts * input.quantity);
  };

  for (const ingredient of ingredients) {
    exact(ingredient.item_id, ratio(ingredient.quantity));
    whole(ingredient.item_id, ingredient.quantity);
    result.depth = Math.max(result.depth, depthOf(ingredient.item_id));
  }
  return result;
}

function units(expansion: Expansion): Ratio {
  return [...expansion.raw.values()].reduce(add, ratio(0));
}

function effort(expansion: Expansion): Ratio {
  return add(
    units(expansion),
    over(expansion.energy, bestFuel.fuel_value ?? 1),
  );
}

describe("the economy's stated curve", () => {
  it("builds industrial stations from earlier suppliers and prices their actual work", () => {
    for (const key of ["smelter", "kiln", "cutter", "crusher", "pump"]) {
      const row = fixture.openings.find(
        (opening) => opening.name === `first ${key}`,
      )!;
      expect(row).toBeDefined();
      expect([...row.construction_order].sort()).toEqual(row.buildings);
      // Every industrial opening owes the founding commission, because material processing is
      // granted by finishing it rather than sold for insight.
      const owed = commissionedRequirements(row.commissions);
      expect(row.commissions).toContain("components");
      const [machineTicks, playerTicks] = stagedOpeningWork(
        row.construction_order,
        owed,
      );
      expect([row.machine_ticks, row.player_work_ticks]).toEqual([
        machineTicks,
        playerTicks,
      ]);
      expect(row.construction_order.indexOf("primitive-furnace")).toBeLessThan(
        row.construction_order.indexOf(key),
      );
      const ingredients = [
        ...row.construction_order.flatMap(
          (name) =>
            catalogue.buildings.find((b) => b.key === name)!.construction_cost,
        ),
        ...owed,
      ];
      const expansion = expand(ingredients);
      expect(row.fuel_energy).toBe(expansion.batchEnergy);
      expect(row.gathers).toEqual(
        [...expansion.batch]
          .sort(([a], [b]) => a - b)
          .map(([id, quantity]) => ({ item: keyOf(id), quantity })),
      );
    }
    const smelter = fixture.openings.find(
      (row) => row.name === "first smelter",
    )!;
    const invalid = smelter.construction_order.filter(
      (key) => key !== "primitive-furnace",
    );
    expect(() => stagedOpeningWork(invalid, [])).toThrow(
      /No machine for iron-plate/,
    );
    const pump = fixture.openings.find((row) => row.name === "first pump")!;
    expect(pump.construction_order.indexOf("kiln")).toBeLessThan(
      pump.construction_order.indexOf("pump"),
    );
  });

  it("funds research out of whole distinct projects", () => {
    // The hub buys a given bill exactly once, so an opening's insight is raised by delivering
    // several different projects rather than by grinding one. Counting fills of a single row would
    // quote a length no player can walk.
    let multi = 0;
    const rows = [
      ...fixture.openings,
      ...fixture.contracts.map((contract) => contract.opening),
    ];
    for (const row of rows) {
      if (row.insight === 0) {
        expect(row.insight_items, row.name).toBe(0);
        expect(row.insight_projects, row.name).toEqual([]);
        continue;
      }
      const named = row.insight_projects.map((key) =>
        catalogue.requests.find((request) => request.key === key),
      );
      expect(
        named.every((request) => request !== undefined),
        `${row.name} names standing projects`,
      ).toBe(true);
      const projects = named.filter((request) => request !== undefined);
      expect(new Set(row.insight_projects).size, row.name).toBe(
        row.insight_projects.length,
      );
      const raised = projects.reduce(
        (sum, request) => sum + request.insight,
        0,
      );
      expect(raised, row.name).toBeGreaterThanOrEqual(row.insight);
      // Whole projects: dropping the last one has to fall short, or the list carries a row the
      // opening never needed.
      const last = projects[projects.length - 1];
      expect(raised - (last?.insight ?? 0), row.name).toBeLessThan(row.insight);
      expect(row.insight_items, row.name).toBe(
        projects.reduce((sum, request) => sum + request.quantity, 0),
      );
      if (projects.length > 1) multi += 1;
    }
    expect(multi, "no opening needs a second project").toBeGreaterThan(0);
  });

  it("funds the whole purchasable tree out of a finite catalogue", () => {
    // The safeguard behind finite demand: once a project retires there is nothing to fall back on,
    // so the catalogue has to cover the tree with enough slack that spending on the wrong branch
    // first is a detour rather than a dead end.
    const budget = fixture.budget;
    expect(budget.project_insight).toBeGreaterThanOrEqual(budget.research_cost);
    expect(budget.surplus_ratio_milli).toBeGreaterThanOrEqual(1250);
    expect(budget.projects).toBe(catalogue.requests.length);
    expect(budget.project_insight).toBe(
      catalogue.requests.reduce((sum, request) => sum + request.insight, 0),
    );
    // Raw rows are the bootstrap, and because each pays once this is their entire lifetime income.
    expect(budget.raw_project_insight).toBeLessThan(budget.research_cost);
    expect(budget.granted_technologies.length).toBeGreaterThan(0);
  });

  it("describes the catalogue it was generated from", () => {
    expect(fixture.reference.definition_version).toBe(catalogue.version);
    expect(fixture.reference.best_fuel_item).toBe(bestFuel.key);
    expect(fixture.reference.best_fuel_value).toBe(bestFuel.fuel_value);
    // Every buildable definition is priced. A new building that never reaches the fixture is a
    // building nothing has ever compared against the curve.
    expect(fixture.buildings.map(({ building }) => building).sort()).toEqual(
      catalogue.buildings
        .filter(({ buildable }) => buildable)
        .map(({ key }) => key)
        .sort(),
    );
    expect(fixture.items.map(({ item }) => item).sort()).toEqual(
      catalogue.items.map(({ key }) => key).sort(),
    );
  });

  it("expands every building cost to the same raw materials TypeScript reaches", () => {
    for (const recorded of fixture.buildings) {
      const building = catalogue.buildings.find(
        ({ key }) => key === recorded.building,
      );
      expect(building, recorded.building).toBeDefined();
      if (!building) continue;
      const expansion = expand(building.construction_cost);

      expect(recorded.depth, `${building.key} depth`).toBe(expansion.depth);
      expect(recorded.raw_units_milli, `${building.key} raw`).toBe(
        milli(units(expansion)),
      );
      expect(recorded.fuel_energy_milli, `${building.key} fuel`).toBe(
        milli(expansion.energy),
      );
      expect(recorded.effort_milli, `${building.key} effort`).toBe(
        milli(effort(expansion)),
      );
      expect(recorded.raw, `${building.key} materials`).toEqual(
        [...expansion.raw]
          .filter(([, quantity]) => quantity.num !== 0)
          .sort(([left], [right]) => left - right)
          .map(([itemId, quantity]) => ({
            item: keyOf(itemId),
            quantity_milli: milli(quantity),
          })),
      );
      // And what a player actually spends, crafting whole batches and eating the leftovers.
      expect(recorded.batch_units, `${building.key} batch`).toBe(
        [...expansion.batch.values()].reduce(
          (total, value) => total + value,
          0,
        ),
      );
      expect(recorded.batch_fuel_energy, `${building.key} batch fuel`).toBe(
        expansion.batchEnergy,
      );
      expect(recorded.machine_ticks, `${building.key} ticks`).toBe(
        expansion.batchTicks,
      );
      // A batch is never cheaper than its proportional share: leftovers are surplus, not a saving.
      expect(recorded.batch_units * 1000).toBeGreaterThanOrEqual(
        recorded.raw_units_milli,
      );
    }
  });

  it("quotes every machine rate at the reference tick rate", () => {
    const tps = fixture.reference.ticks_per_second;
    for (const machine of fixture.machines) {
      const building = catalogue.buildings.find(
        ({ key }) => key === machine.building,
      );
      expect(building, machine.building).toBeDefined();
      if (!building) continue;
      expect(machine.power_draw).toBe(building.power_draw ?? 0);
      if (machine.recipe === null) {
        // An extractor's cycle comes from the material, scaled by the building's own speed; a
        // pump still runs on its cadence, because water has no per-material figure.
        const dug = catalogue.items.find(
          ({ key }) => key === machine.output_item,
        );
        const steps =
          building.kind === "extractor" ? dug?.extract_steps : undefined;
        if (steps !== undefined) {
          const speed = building.extract_speed ?? 100;
          expect(machine.ticks_per_cycle).toBe(
            Math.max(1, Math.ceil((steps * 100) / speed)),
          );
        } else {
          expect(machine.ticks_per_cycle).toBe(building.cadence ?? 1);
        }
        expect(machine.output_per_cycle).toBe(1);
      } else {
        const recipe = catalogue.recipes.find(
          ({ key }) => key === machine.recipe,
        );
        expect(recipe, machine.recipe ?? "").toBeDefined();
        if (!recipe) continue;
        // A machine only runs recipes of its own category. That is the check that stops a kiln
        // being quoted at a smelter's rate.
        expect(
          building.recipe_ids
            ? building.recipe_ids.includes(recipe.id)
            : recipe.category === building.recipe_category,
        ).toBe(true);
        expect(machine.ticks_per_cycle).toBe(
          recipe.duration * (building.duration_multiplier ?? 1),
        );
        expect(machine.output_per_cycle).toBe(recipe.output.quantity);
        expect(machine.fuel_energy_per_cycle).toBe(recipe.fuel ?? 0);
      }
      expect(machine.per_minute_milli).toBe(
        milli(
          over(
            ratio(machine.output_per_cycle * 60 * tps),
            machine.ticks_per_cycle,
          ),
        ),
      );
    }
  });

  it("never lets a fuel conversion hand back more than it burned", () => {
    for (const entry of fixture.fuel) {
      const item = catalogue.items.find(({ key }) => key === entry.item);
      expect(item?.fuel_value).toBe(entry.fuel_value);
      if (entry.recipe === null) continue;
      const recipe = catalogue.recipes.find(({ key }) => key === entry.recipe);
      expect(recipe, entry.recipe ?? "").toBeDefined();
      if (!recipe) continue;
      const input =
        (recipe.fuel ?? 0) +
        recipe.inputs.reduce(
          (total, ingredient) =>
            total +
            ingredient.quantity *
              (itemById.get(ingredient.item_id)?.fuel_value ?? 0),
          0,
        );
      expect(entry.input_energy).toBe(input);
      expect(entry.output_energy).toBe(
        entry.fuel_value * recipe.output.quantity,
      );
      // Charcoal made energy from nothing through v0.23: two wood at two energy for one charcoal
      // at eight, from a kiln that burns no fuel, on an input that regrows. A real kiln burns part
      // of the charge to cook the rest and keeps a quarter to a half — the recipe is bought for
      // density, four times the energy in one belt slot, never for energy itself.
      expect(entry.output_energy, entry.item).toBeLessThanOrEqual(input);
      expect(entry.output_energy * 4, entry.item).toBeGreaterThanOrEqual(input);
    }
  });

  it("holds every step of the curve it states", () => {
    expect(fixture.curve.length).toBeGreaterThan(0);
    for (const step of fixture.curve) {
      expect(
        step.holds,
        `${step.building} follows ${step.follows} by ${step.relation}`,
      ).toBe(true);
      const strictly = step.relation === "upgrade";
      expect(step.effort_milli).toBeGreaterThanOrEqual(
        step.follows_effort_milli + (strictly ? 1 : 0),
      );
    }
    // The ladders are in it: an upgrade that cost no more than the tier below would be a free
    // machine, and both shipped ladders have to appear as upgrade steps.
    const upgrades = fixture.curve.filter(
      ({ relation }) => relation === "upgrade",
    );
    expect(upgrades.map(({ building }) => building).sort()).toEqual(
      catalogue.buildings
        .filter(({ upgrades_to }) => upgrades_to !== undefined)
        .map(
          ({ upgrades_to }) =>
            catalogue.buildings.find(({ id }) => id === upgrades_to)?.key ?? "",
        )
        .sort(),
    );
  });

  it("prices the landing hub's own contract through the same tree", () => {
    // The bill a founding project states is a claim about the whole tree under it, and the tree is
    // where the claim can be wrong: `16 iron plate` says nothing about the thirty-two ore beneath
    // it. TypeScript expands the shipped scenario independently and has to reach the same numbers,
    // so the fixture is pinned by two expansions rather than by Rust agreeing with itself.
    const stages = (
      scenarios as unknown as {
        scenarios: {
          key: string;
          contract: {
            key: string;
            stages: { key: string; requirements: Ingredient[] }[];
          };
        }[];
      }
    ).scenarios.flatMap((scenario) =>
      scenario.contract.stages
        .filter((stage) =>
          stage.requirements.every((need) => need.quantity <= 10_000),
        )
        .map((stage) => ({ scenario: scenario.key, stage })),
    );
    expect(fixture.contracts).toHaveLength(stages.length);
    for (const { scenario, stage } of stages) {
      const row = fixture.contracts.find(
        (value) => value.scenario === scenario && value.stage === stage.key,
      );
      expect(
        row,
        `${scenario}/${stage.key} is missing from the fixture`,
      ).toBeDefined();
      if (!row) continue;
      expect(row.bill).toEqual(
        stage.requirements.map((need) => ({
          item: keyOf(need.item_id),
          quantity: need.quantity,
        })),
      );
      const expansion = expand(stage.requirements);
      expect(row.raw_materials).toBe(expansion.raw.size);
      // A stage never commissions itself, or nothing would resolve; it can owe an earlier one.
      expect(row.opening.commissions).not.toContain(stage.key);
      const owed = commissionedRequirements(row.opening.commissions);
      const ingredients = [
        ...stage.requirements,
        ...owed,
        ...catalogue.buildings
          .filter((building) => row.opening.buildings.includes(building.key))
          .flatMap((building) => building.construction_cost),
      ];
      const [machineTicks, playerTicks] = stagedOpeningWork(
        row.opening.construction_order,
        [...stage.requirements, ...owed],
      );
      expect(row.opening.machine_ticks).toBe(machineTicks);
      expect(row.opening.player_work_ticks).toBe(playerTicks);
      expect(row.opening.player_work_seconds_milli).toBe(
        (playerTicks * 1000) / fixture.reference.ticks_per_second,
      );
      // The opening's fuel is the fuel under everything it takes to stand the stage up, stations
      // included — not the fuel under the bill alone. The two were the same number while every
      // station was billed in ore and stone, which burn nothing; a station billed in iron plate
      // brings a smelter's coal with it, so the comparison has to be made against the same list of
      // ingredients `openingWork` is given.
      expect(row.opening.fuel_energy).toBe(expand(ingredients).batchEnergy);
    }

    // And the project the hub actually builds is a project: more than one landscape, and dearer
    // than the beat that proves the line.
    const founding = fixture.contracts.filter(
      (row) => row.scenario === "new-game",
    );
    expect(founding.length).toBeGreaterThanOrEqual(2);
    const first = founding[0];
    const last = founding[founding.length - 1];
    expect(last?.raw_materials).toBeGreaterThanOrEqual(2);
    expect(last?.opening.gather_total).toBeGreaterThan(
      first?.opening.gather_total ?? 0,
    );
  });

  it("prices the player's own hands against the machine that replaces them", () => {
    // The rule this pins is the reverse of the one v0.23 shipped. A tier-one extractor is *half*
    // the hand on the same material, and the deep extractor is what finally draws level. The
    // trade an extractor offers is no longer speed, it is that it works while the player is
    // somewhere else — which is what makes automation a question of how many you can afford.
    const rateFor = (building: string, item: string) =>
      fixture.machines.find(
        (machine) =>
          machine.building === building && machine.output_item === item,
      )?.per_minute_milli ?? 0;

    for (const gather of fixture.reference.hand_gathers) {
      const hand = gather.items_per_minute * 1000;
      const tierOne = rateFor("extractor", gather.item);
      const deep = rateFor("extractor-ii", gather.item);
      expect(
        tierOne,
        `${gather.item} needs a tier-one extractor row`,
      ).toBeGreaterThan(0);
      expect(deep, `${gather.item} needs a deep extractor row`).toBeGreaterThan(
        0,
      );
      // Half, within the rounding a whole number of ticks allows: sand and clay want 13.33 ticks
      // and get 13, which is the only place the ladder is not exact.
      expect(
        tierOne,
        `${gather.item} tier one is half the hand`,
      ).toBeGreaterThan(hand * 0.45);
      expect(tierOne, `${gather.item} tier one is half the hand`).toBeLessThan(
        hand * 0.55,
      );
      // The upgrade is what reaches the hand, and it may pass it.
      expect(deep, `${gather.item} deep extractor draws level`).toBeGreaterThan(
        hand * 0.94,
      );
      expect(
        deep / tierOne,
        `${gather.item} deep is twice tier one`,
      ).toBeGreaterThan(1.8);
      expect(
        (60 * fixture.reference.player_ticks_per_second) / gather.steps,
      ).toBe(gather.items_per_minute);
    }

    // Crystal is the one material with an extraction rate and no hand rate at all, and it is the
    // slowest thing an extractor digs: twice the ore it sits beside in the highland.
    expect(
      fixture.reference.hand_gathers.some(({ item }) => item === "crystal"),
    ).toBe(false);
    expect(rateFor("extractor", "crystal")).toBeGreaterThan(0);
    expect(rateFor("extractor", "crystal") * 2).toBe(
      rateFor("extractor", "ore"),
    );

    const wood = fixture.reference.hand_gathers.find(
      ({ item }) => item === "wood",
    );
    expect(wood, "wood is the fastest hand").toBeDefined();
    expect(fixture.reference.gather_cooldown_steps).toBe(wood?.steps);
    expect(fixture.reference.hand_items_per_minute).toBe(
      wood?.items_per_minute,
    );
  });

  it("prices every hand-gathered project below every processed one", () => {
    // Per gather, which is the rate a player can actually improve. Raw rows still pay better per
    // *minute* — a gather is quick and a furnace is not — and that is fine now demand is finite:
    // the whole hand-gathered catalogue is 73 insight against 120 of research, so hand-gathering
    // cannot substitute for processing however fast it runs. It buys time, not the tree.
    const handable = new Set(
      fixture.reference.hand_gathers.map(({ item }) => item),
    );
    const raw = fixture.requests.filter(
      (request) => request.machine_ticks === 0 && handable.has(request.item),
    );
    const processed = fixture.requests.filter(
      (request) => request.machine_ticks > 0,
    );
    expect(raw.length).toBeGreaterThanOrEqual(7);
    const bestRawGather = Math.max(
      ...raw.map((request) => request.insight_per_gather_milli),
    );
    for (const request of processed) {
      expect(
        request.insight_per_gather_milli,
        `${request.request} per gather`,
      ).toBeGreaterThan(bestRawGather);
    }
    const rawInsight = raw.reduce(
      (total, request) => total + request.insight,
      0,
    );
    expect(rawInsight).toBeLessThan(fixture.budget.research_cost);
  });
});

it("budgets personal skill points separately from factory insight", () => {
  expect(fixture.budget.skill_points).toBe(3);
  expect(fixture.budget.skill_cost).toBe(2);
  expect(fixture.budget.skill_milestones).toBe(3);
  expect(fixture.budget.research_cost).toBe(120);
  expect(fixture.budget.project_insight).toBe(572);
});

describe("primitive boundary construction", () => {
  it("prices boundaries and a nine-hex yard using reachable manual production", () => {
    for (const project of fixture.boundaries) {
      const direct = project.direct.map((i) => ({
        item_id: catalogue.items.find((d) => d.key === i.item)!.id,
        quantity: i.quantity,
      }));
      expect(
        openingWork(direct, ["manual-workshop", "primitive-furnace"]),
      ).toEqual([project.process_ticks, project.attended_ticks]);
      expect(
        project.direct.every((i) => !["ore", "copper-ore"].includes(i.item)),
      ).toBe(true);
    }
    const fence = catalogue.boundaries.find((b) => b.key === "timber-fence")!;
    const gate = catalogue.boundaries.find((b) => b.key === "timber-gate")!;
    const yard = fixture.boundaries.find(
      (b) => b.project === "nine-hex-yard-with-gate",
    )!;
    const bill = new Map<number, number>();
    for (const [boundary, count] of [
      [fence, 21],
      [gate, 1],
    ] as const)
      for (const item of boundary.construction_cost)
        bill.set(
          item.item_id,
          (bill.get(item.item_id) ?? 0) + item.quantity * count,
        );
    expect(yard.direct).toEqual(
      [...bill].map(([id, quantity]) => ({
        item: catalogue.items.find((i) => i.id === id)!.key,
        quantity,
      })),
    );
  });
});

describe("prepared ground", () => {
  it("prices a paved yard against the walking it actually saves", () => {
    // Native's own constants, restated once so this side is an independent expansion rather than a
    // second reading of the same source: a step costs 100, untreated ground walks at 100, and no
    // surface may exceed 150 or the route search's heuristic stops being admissible.
    const stepCost = 100;
    const untreated = 100;
    for (const surface of fixture.surfaces) {
      const definition = catalogue.surfaces.find(
        (s) => s.key === surface.surface,
      )!;
      expect(surface.movement).toBe(definition.movement);
      expect(surface.movement).toBeGreaterThanOrEqual(untreated);
      expect(surface.movement).toBeLessThanOrEqual(150);
      // Integer arithmetic, floored, because the route search and the player's feet must divide the
      // same way. A float here would let a paved route cost one thing to plan and another to walk.
      expect(surface.step_cost).toBe(
        Math.floor((stepCost * untreated) / surface.movement),
      );
      expect(surface.hexes_saved_per_hundred_milli).toBe(
        100_000 - (surface.step_cost * 100_000) / stepCost,
      );
      // A surface is bought by the hex, so the yard's bill is the unit bill times its nine hexes.
      expect(surface.direct).toEqual(
        definition.construction_cost.map((item) => ({
          item: catalogue.items.find((i) => i.id === item.item_id)!.key,
          quantity: item.quantity * surface.hexes,
        })),
      );
      expect(
        surface.direct.every((i) => !["ore", "copper-ore"].includes(i.item)),
      ).toBe(true);
    }
    // The cheapest surface is free and the fastest is not, so the ladder is a real choice rather
    // than a single correct answer the player is expected to find.
    expect(
      fixture.surfaces.find((s) => s.surface === "compacted-earth")!.direct,
    ).toEqual([]);
    expect(
      Math.max(...fixture.surfaces.map((s) => s.movement)),
    ).toBeGreaterThan(untreated);
  });
});
