import { describe, expect, it } from "vitest";

import fixture from "../fixtures/balance.json";
import definitions from "../src/data/definitions.json";
import scenarios from "../src/data/scenarios.json";
import type { Definitions, Ingredient } from "../src/core/types";

/**
 * The cross-language half of the balance gate.
 *
 * `fixtures/balance.json` is generated by Rust from the shipped catalogues, and the Rust suite
 * asserts it computes exactly those numbers. This side recomputes the parts that are pure
 * arithmetic over `definitions.json` — the recipe-tree expansion, the fuel round trip, the machine
 * rates — from scratch, and asserts it lands on the same figures. Two independent expansions
 * agreeing is what makes the fixture evidence; one implementation agreeing with its own output
 * would only say the file was written.
 *
 * The parts that are not pure arithmetic over the catalogue — what a world preset actually
 * generates, what an extraction site is worth — stay Rust's, because they are the generator's
 * answers and re-deriving those here would be a second world generator.
 *
 * If this fails after a deliberate tuning pass, regenerate with
 * `UPDATE_BALANCE_FIXTURE=1 cargo test balance_fixture` and read the diff.
 */

const catalogue = definitions as Definitions;

// Exact rationals, for the same reason Rust uses them: a kiln fires three bricks at once, so a
// pump that wants four of them costs four thirds of a batch, and rounding that at every step of a
// tree and then comparing two buildings compares rounding errors.
interface Ratio {
  num: number;
  den: number;
}

function gcd(a: number, b: number): number {
  return b === 0 ? Math.max(a, 1) : gcd(b, a % b);
}

function ratio(num: number, den = 1): Ratio {
  const divisor = gcd(Math.abs(num), Math.abs(den));
  return { num: num / divisor, den: den / divisor };
}

function add(left: Ratio, right: Ratio): Ratio {
  return ratio(
    left.num * right.den + right.num * left.den,
    left.den * right.den,
  );
}

function times(value: Ratio, factor: number): Ratio {
  return ratio(value.num * factor, value.den);
}

function over(value: Ratio, divisor: number): Ratio {
  return ratio(value.num, value.den * divisor);
}

/** Thousandths, rounded half up — the same one rounding, at the same edge, Rust applies. */
function milli(value: Ratio): number {
  return Math.floor((value.num * 1000 + Math.floor(value.den / 2)) / value.den);
}

const itemById = new Map(catalogue.items.map((item) => [item.id, item]));
const recipeFor = new Map(
  catalogue.recipes.map((recipe) => [recipe.output.item_id, recipe]),
);
const keyOf = (id: number) => itemById.get(id)?.key ?? `item-${id}`;

const bestFuel = catalogue.items
  .filter((item) => item.fuel_value)
  .reduce((best, item) =>
    (item.fuel_value ?? 0) > (best.fuel_value ?? 0) ? item : best,
  );

interface Expansion {
  raw: Map<number, Ratio>;
  energy: Ratio;
  ticks: Ratio;
  batch: Map<number, number>;
  batchEnergy: number;
  batchTicks: number;
  depth: number;
}

function depthOf(itemId: number): number {
  const recipe = recipeFor.get(itemId);
  if (!recipe) return 0;
  return 1 + Math.max(...recipe.inputs.map((input) => depthOf(input.item_id)));
}

function expand(ingredients: Ingredient[]): Expansion {
  const result: Expansion = {
    raw: new Map(),
    energy: ratio(0),
    ticks: ratio(0),
    batch: new Map(),
    batchEnergy: 0,
    batchTicks: 0,
    depth: 0,
  };

  const exact = (itemId: number, quantity: Ratio) => {
    const recipe = recipeFor.get(itemId);
    if (!recipe) {
      result.raw.set(itemId, add(result.raw.get(itemId) ?? ratio(0), quantity));
      return;
    }
    const crafts = over(quantity, Math.max(recipe.output.quantity, 1));
    result.energy = add(result.energy, times(crafts, recipe.fuel ?? 0));
    result.ticks = add(result.ticks, times(crafts, recipe.duration));
    for (const input of recipe.inputs)
      exact(input.item_id, times(crafts, input.quantity));
  };

  const whole = (itemId: number, quantity: number) => {
    const recipe = recipeFor.get(itemId);
    if (!recipe) {
      result.batch.set(itemId, (result.batch.get(itemId) ?? 0) + quantity);
      return;
    }
    const crafts = Math.ceil(quantity / Math.max(recipe.output.quantity, 1));
    result.batchEnergy += crafts * (recipe.fuel ?? 0);
    result.batchTicks += crafts * recipe.duration;
    for (const input of recipe.inputs)
      whole(input.item_id, crafts * input.quantity);
  };

  for (const ingredient of ingredients) {
    exact(ingredient.item_id, ratio(ingredient.quantity));
    whole(ingredient.item_id, ingredient.quantity);
    result.depth = Math.max(result.depth, depthOf(ingredient.item_id));
  }
  return result;
}

function units(expansion: Expansion): Ratio {
  return [...expansion.raw.values()].reduce(add, ratio(0));
}

function effort(expansion: Expansion): Ratio {
  return add(
    units(expansion),
    over(expansion.energy, bestFuel.fuel_value ?? 1),
  );
}

describe("the economy's stated curve", () => {
  it("describes the catalogue it was generated from", () => {
    expect(fixture.reference.definition_version).toBe(catalogue.version);
    expect(fixture.reference.best_fuel_item).toBe(bestFuel.key);
    expect(fixture.reference.best_fuel_value).toBe(bestFuel.fuel_value);
    // Every buildable definition is priced. A new building that never reaches the fixture is a
    // building nothing has ever compared against the curve.
    expect(fixture.buildings.map(({ building }) => building).sort()).toEqual(
      catalogue.buildings
        .filter(({ buildable }) => buildable)
        .map(({ key }) => key)
        .sort(),
    );
    expect(fixture.items.map(({ item }) => item).sort()).toEqual(
      catalogue.items.map(({ key }) => key).sort(),
    );
  });

  it("expands every building cost to the same raw materials TypeScript reaches", () => {
    for (const recorded of fixture.buildings) {
      const building = catalogue.buildings.find(
        ({ key }) => key === recorded.building,
      );
      expect(building, recorded.building).toBeDefined();
      if (!building) continue;
      const expansion = expand(building.construction_cost);

      expect(recorded.depth, `${building.key} depth`).toBe(expansion.depth);
      expect(recorded.raw_units_milli, `${building.key} raw`).toBe(
        milli(units(expansion)),
      );
      expect(recorded.fuel_energy_milli, `${building.key} fuel`).toBe(
        milli(expansion.energy),
      );
      expect(recorded.effort_milli, `${building.key} effort`).toBe(
        milli(effort(expansion)),
      );
      expect(recorded.raw, `${building.key} materials`).toEqual(
        [...expansion.raw]
          .filter(([, quantity]) => quantity.num !== 0)
          .sort(([left], [right]) => left - right)
          .map(([itemId, quantity]) => ({
            item: keyOf(itemId),
            quantity_milli: milli(quantity),
          })),
      );
      // And what a player actually spends, crafting whole batches and eating the leftovers.
      expect(recorded.batch_units, `${building.key} batch`).toBe(
        [...expansion.batch.values()].reduce(
          (total, value) => total + value,
          0,
        ),
      );
      expect(recorded.batch_fuel_energy, `${building.key} batch fuel`).toBe(
        expansion.batchEnergy,
      );
      expect(recorded.machine_ticks, `${building.key} ticks`).toBe(
        expansion.batchTicks,
      );
      // A batch is never cheaper than its proportional share: leftovers are surplus, not a saving.
      expect(recorded.batch_units * 1000).toBeGreaterThanOrEqual(
        recorded.raw_units_milli,
      );
    }
  });

  it("quotes every machine rate at the reference tick rate", () => {
    const tps = fixture.reference.ticks_per_second;
    for (const machine of fixture.machines) {
      const building = catalogue.buildings.find(
        ({ key }) => key === machine.building,
      );
      expect(building, machine.building).toBeDefined();
      if (!building) continue;
      expect(machine.power_draw).toBe(building.power_draw ?? 0);
      if (machine.recipe === null) {
        expect(machine.ticks_per_cycle).toBe(building.cadence ?? 1);
        expect(machine.output_per_cycle).toBe(1);
      } else {
        const recipe = catalogue.recipes.find(
          ({ key }) => key === machine.recipe,
        );
        expect(recipe, machine.recipe ?? "").toBeDefined();
        if (!recipe) continue;
        // A machine only runs recipes of its own category. That is the check that stops a kiln
        // being quoted at a smelter's rate.
        expect(recipe.category).toBe(building.recipe_category);
        expect(machine.ticks_per_cycle).toBe(recipe.duration);
        expect(machine.output_per_cycle).toBe(recipe.output.quantity);
        expect(machine.fuel_energy_per_cycle).toBe(recipe.fuel ?? 0);
      }
      expect(machine.per_minute_milli).toBe(
        milli(
          over(
            ratio(machine.output_per_cycle * 60 * tps),
            machine.ticks_per_cycle,
          ),
        ),
      );
    }
  });

  it("keeps a fuel conversion ahead of what it burned", () => {
    for (const entry of fixture.fuel) {
      const item = catalogue.items.find(({ key }) => key === entry.item);
      expect(item?.fuel_value).toBe(entry.fuel_value);
      if (entry.recipe === null) continue;
      const recipe = catalogue.recipes.find(({ key }) => key === entry.recipe);
      expect(recipe, entry.recipe ?? "").toBeDefined();
      if (!recipe) continue;
      const input =
        (recipe.fuel ?? 0) +
        recipe.inputs.reduce(
          (total, ingredient) =>
            total +
            ingredient.quantity *
              (itemById.get(ingredient.item_id)?.fuel_value ?? 0),
          0,
        );
      expect(entry.input_energy).toBe(input);
      expect(entry.output_energy).toBe(
        entry.fuel_value * recipe.output.quantity,
      );
      // Charcoal returned exactly what it was given through v0.16: two wood at two energy for one
      // charcoal at four, costing a kiln, ten ticks, and a hundred power to break even.
      expect(entry.output_energy, entry.item).toBeGreaterThan(input);
    }
  });

  it("holds every step of the curve it states", () => {
    expect(fixture.curve.length).toBeGreaterThan(0);
    for (const step of fixture.curve) {
      expect(
        step.holds,
        `${step.building} follows ${step.follows} by ${step.relation}`,
      ).toBe(true);
      const strictly = step.relation === "upgrade";
      expect(step.effort_milli).toBeGreaterThanOrEqual(
        step.follows_effort_milli + (strictly ? 1 : 0),
      );
    }
    // The ladders are in it: an upgrade that cost no more than the tier below would be a free
    // machine, and both shipped ladders have to appear as upgrade steps.
    const upgrades = fixture.curve.filter(
      ({ relation }) => relation === "upgrade",
    );
    expect(upgrades.map(({ building }) => building).sort()).toEqual(
      catalogue.buildings
        .filter(({ upgrades_to }) => upgrades_to !== undefined)
        .map(
          ({ upgrades_to }) =>
            catalogue.buildings.find(({ id }) => id === upgrades_to)?.key ?? "",
        )
        .sort(),
    );
  });

  it("prices the landing hub's own contract through the same tree", () => {
    // The bill a founding project states is a claim about the whole tree under it, and the tree is
    // where the claim can be wrong: `16 iron plate` says nothing about the thirty-two ore beneath
    // it. TypeScript expands the shipped scenario independently and has to reach the same numbers,
    // so the fixture is pinned by two expansions rather than by Rust agreeing with itself.
    const stages = (
      scenarios as unknown as {
        scenarios: {
          key: string;
          contract: {
            key: string;
            stages: { key: string; requirements: Ingredient[] }[];
          };
        }[];
      }
    ).scenarios.flatMap((scenario) =>
      scenario.contract.stages
        .filter((stage) =>
          stage.requirements.every((need) => need.quantity <= 10_000),
        )
        .map((stage) => ({ scenario: scenario.key, stage })),
    );
    expect(fixture.contracts).toHaveLength(stages.length);
    for (const { scenario, stage } of stages) {
      const row = fixture.contracts.find(
        (value) => value.scenario === scenario && value.stage === stage.key,
      );
      expect(
        row,
        `${scenario}/${stage.key} is missing from the fixture`,
      ).toBeDefined();
      if (!row) continue;
      expect(row.bill).toEqual(
        stage.requirements.map((need) => ({
          item: keyOf(need.item_id),
          quantity: need.quantity,
        })),
      );
      const expansion = expand(stage.requirements);
      expect(row.raw_materials).toBe(expansion.raw.size);
      expect(row.opening.machine_ticks).toBe(expansion.batchTicks);
      expect(row.opening.fuel_energy).toBe(expansion.batchEnergy);
    }

    // And the project the hub actually builds is a project: more than one landscape, and dearer
    // than the beat that proves the line.
    const founding = fixture.contracts.filter(
      (row) => row.scenario === "new-game",
    );
    expect(founding.length).toBeGreaterThanOrEqual(2);
    const first = founding[0];
    const last = founding[founding.length - 1];
    expect(last?.raw_materials).toBeGreaterThanOrEqual(2);
    expect(last?.opening.gather_total).toBeGreaterThan(
      first?.opening.gather_total ?? 0,
    );
  });

  it("prices the player's own hands against the machine that replaces them", () => {
    const extractor = fixture.machines.find(
      ({ building }) => building === "extractor",
    );
    expect(extractor?.per_minute_milli).toBe(
      fixture.reference.hand_items_per_minute * 1000,
    );
    // The hand's rate is real time, not factory time, so it is the one figure the speed control
    // does not move — which is exactly why it had to be written down beside one that it does.
    expect(fixture.reference.gather_cooldown_steps).toBeGreaterThan(0);
    expect(
      (60 * fixture.reference.player_ticks_per_second) /
        fixture.reference.gather_cooldown_steps,
    ).toBe(fixture.reference.hand_items_per_minute);
  });
});
