import { describe, expect, it } from "vitest";

import fixture from "../fixtures/snapshot-delta-wire.json";
import { decodeSnapshotDelta } from "../src/core/snapshotWire";

/**
 * The cross-language half of the wire gate.
 *
 * `fixtures/snapshot-delta-wire.json` is generated by Rust, which asserts it encodes those deltas
 * to exactly those bytes and serializes them to exactly that JSON. This asserts the shipped
 * decoder turns the same bytes back into the same JSON. Between them the two say the binary path
 * delivers what the JSON path delivered, which is the entire claim the encoding rests on: the host,
 * the renderer, and every test above them were written against the JSON shape and none of them
 * changed.
 *
 * The Rust suite covers the other axis — `dirty_tracked_deltas_match_a_full_snapshot_diff` round
 * trips every delta a running factory produces, which reaches entity and group combinations no
 * hand-written fixture enumerates.
 *
 * If this fails after a format change, regenerate with
 * `UPDATE_WIRE_FIXTURE=1 cargo test wire_fixture` and move the decoder to match.
 */

function bytesOf(hex: string): ArrayBuffer {
  const bytes = new Uint8Array(hex.length / 2);
  for (let index = 0; index < bytes.length; index += 1) {
    bytes[index] = Number.parseInt(hex.slice(index * 2, index * 2 + 2), 16);
  }
  return bytes.buffer;
}

describe("binary snapshot delta", () => {
  it("agrees with the Rust encoder on the format's identity", () => {
    expect(fixture.magic).toBe("HXFD");
    expect(fixture.version).toBe(17);
  });

  it("reads prepared ground as a signed grade beside an unsigned surface", () => {
    // Elevation is signed and a surface id is not, so the two use different varint readers. Reading
    // a cut cell with the unsigned one does not fail — it returns a vast positive number — so the
    // fixture carries a paved cell and a cut cell together and this pins both back.
    const decoded = decodeSnapshotDelta(
      bytesOf(
        fixture.cases.find((test) => test.name === "prepared ground and spoil")!
          .bytes,
      ),
    );
    expect(decoded.ground).toEqual([
      {
        q: 2,
        r: -3,
        surface: 4,
        elevation: 0,
        paid: [{ item_id: 15, quantity: 1 }],
      },
      { q: -1, r: 0, surface: 0, elevation: -2, paid: [] },
    ]);
    expect(decoded.spoil).toBe(6);
  });

  it.each(fixture.cases)("decodes $name to exactly the JSON delta", (test) => {
    expect(decodeSnapshotDelta(bytesOf(test.bytes))).toEqual(test.delta);
  });

  it("reads every closed set the wire carries as a code", () => {
    // The tables are indexed by wire code in both languages, so a reordering on either side is a
    // silent mistranslation — a belt drawn as a pump — rather than a decode failure. The fixture
    // carries Rust's order and this pins the decoder's against it.
    const decoded = decodeSnapshotDelta(
      bytesOf(
        fixture.cases.find((test) => test.name === "both patches with entries")!
          .bytes,
      ),
    );
    expect(decoded.buildings?.changed?.map((entity) => entity.kind)).toEqual([
      "belt",
      "composer",
    ]);
    expect(decoded.buildings?.changed?.map((entity) => entity.status)).toEqual([
      "idle",
      "composing",
    ]);
    expect(decoded.terrain?.map((tile) => tile.terrain)).toEqual([
      "cliff",
      "deep_water",
    ]);
  });

  it("carries an integer up to the largest one the host can hold", () => {
    // The wire invariant is that nothing wider than 2^53 travels as a number. The fixture pins the
    // boundary itself, so a varint reader that used `<<` — which truncates to 32 bits — cannot pass.
    const decoded = decodeSnapshotDelta(
      bytesOf(
        fixture.cases.find((test) => test.name === "every scalar group")!.bytes,
      ),
    );
    expect(decoded.delivered).toBe(Number.MAX_SAFE_INTEGER);
    expect(decoded.tick).toBe(300);
  });

  it("refuses a buffer it cannot prove it understands", () => {
    const good = new Uint8Array(
      bytesOf(fixture.cases[0]!.bytes as unknown as string),
    );

    const foreign = good.slice();
    foreign[0] = 0x00;
    expect(() => decodeSnapshotDelta(foreign.buffer)).toThrow(
      /not a HexFactory wire payload/,
    );

    // A core built against a later format would otherwise be decoded as if it were this one, which
    // produces a plausible wrong world rather than an error.
    const future = good.slice();
    future[4] = 99;
    expect(() => decodeSnapshotDelta(future.buffer)).toThrow(
      /Unsupported snapshot delta wire version 99/,
    );

    const truncated = good.slice(0, good.length - 1);
    expect(() => decodeSnapshotDelta(truncated.buffer)).toThrow();

    const trailing = new Uint8Array(good.length + 1);
    trailing.set(good);
    expect(() => decodeSnapshotDelta(trailing.buffer)).toThrow(
      /trailing bytes/,
    );
  });
});
